
/*
 * Warning.
 * Do not edit this file.  It is generated from data/apps.yaml
 * ...edit that file instead.
 */

var json = {
  "id": 0, 
  "data": {
    "description": "Ce projet n'est plus maintenu, vous pouvez trouver des informations sur <a href=\"http://hemoreg.me\">mon site personnel</a>.\n"
  }, 
  "name": "Jérôme GIL", 
  "ipv6_only": false, 
  "children": [
    {
      "id": 1, 
      "data": {
        "description": "Toutes les informations qui faut connaître sur moi.\n"
      }, 
      "name": "A Propos", 
      "ipv6_only": false, 
      "children": [
        {
          "data": {
            "url": null, 
            "description": "Je suis né le <em>28 Mai 1997</em> à <em>Toulouse</em>. J'ai donc en ce moment <em>21 ans</em>. Nationnalité <em>Fran\u00e7aise</em>.\n", 
            "icon": "apropos.png"
          }, 
          "name": "Identité", 
          "ipv6_only": false, 
          "id": 2
        }, 
        {
          "data": {
            "url": null, 
            "description": "Originaire de Toulouse, je peux me déplacer dans cette ville facilement. Domicilié à Lyon. Mail : LinkJerome@gmail.com Tel : +33.(0)6.36.69.98.55\n", 
            "icon": "mail.png"
          }, 
          "name": "Adresses", 
          "ipv6_only": false, 
          "id": 3
        }, 
        {
          "data": {
            "url": "https://www.linkedin.com/in/jerome-gil/", 
            "description": "Si vous souhaitez me suivre ou me contacter via Linkedin, vous pouvez cliquer sur le lien suivant !\n", 
            "icon": "linkedin.png"
          }, 
          "name": "Linkedin", 
          "ipv6_only": false, 
          "id": 4
        }, 
        {
          "data": {
            "url": "https://drive.google.com/file/d/1_4JOBAcAKbD9dOq7NC0SUBnUvbpIQ-dj/view?usp=sharing", 
            "description": "Vous trouverez ci-joint le PDF de mon CV afin de pouvoir l'afficher et éventuellement l'imprimer !\n", 
            "icon": "resume.png"
          }, 
          "name": "CV PDF", 
          "ipv6_only": false, 
          "id": 5
        }
      ]
    }, 
    {
      "id": 6, 
      "data": {
        "description": "Quelles sont les formations que j'ai effectuées ? Tout est expliqué dans cette catégorie !\n"
      }, 
      "name": "Formations", 
      "ipv6_only": false, 
      "children": [
        {
          "data": {
            "url": null, 
            "description": "<em>Sept 2016 - Juin 2019</em>Une solide formation en Informatique et mathématiques sur 3 ans ; une ouverture en économie, une culture générale (langue, handicaps, sport ...) ainsi qu'un stage en entreprise.\n", 
            "icon": null
          }, 
          "name": "Licence en informatique", 
          "ipv6_only": false, 
          "id": 7
        }, 
        {
          "data": {
            "url": "https://www.sncf.com/fr/emploi/nos-metiers/commercial-a-bord-des-trains", 
            "description": "<em>Mai 2016 - Juin 2016</em>Connaissances approfondies du code de circulation des trains. Formation prévention accident, incendies et sécurité ferroviaire afin de pouvoir assurer la sécurité des voyageurs.\n", 
            "icon": "voyage.png"
          }, 
          "name": "Habilitation Sécurité", 
          "ipv6_only": false, 
          "id": 8
        }
      ]
    }, 
    {
      "id": 9, 
      "data": {
        "description": "J'ai eu l'occasion de pouvoir travailler dans différentes structures afin de me former et de développer mes compétences professionnelles. Pour les connaître, continuez dans cette catégorie.\n"
      }, 
      "name": "Experiences", 
      "ipv6_only": false, 
      "children": [
        {
          "data": {
            "url": "https://www.sncf.com/fr/emploi/nos-metiers/commercial-a-bord-des-trains", 
            "description": "<em>Mai 2016 - Actuel</em> ASCT Auxiliaire dans les gares de Toulouse Matabiau et Lyon Perrache, les principales missions sont :\n  <ul>\n    <li>Gérer une équipe.</li>\n    <li>Vente et Vérification de titre de transport.</li>\n    <li>Assurer la sécurité des trains et des voyageurs.</li>\n  </ul>\n", 
            "icon": "voyage.png"
          }, 
          "name": "Agent Service Commercial Train", 
          "ipv6_only": false, 
          "id": 10
        }, 
        {
          "data": {
            "url": null, 
            "description": "<em>Mai 2014 - Mai 2016</em> Responsable buvette dans une association à but non-lucratif de jeu de carte \"Magic The Gathering\". J'ai pu faire essentiellement :\n <ul>\n   <li>Vente et gestion des stocks.</li>\n   <li>Préparation des Sandwichs et service.</li>\n   <li>Management.</li>\n </ul>\n", 
            "icon": "bar.png"
          }, 
          "name": "Responsable Buvette", 
          "ipv6_only": false, 
          "id": 11
        }, 
        {
          "data": {
            "url": "http://www.education.gouv.fr/vie-lyceenne/cid73077/le-conseil-des-delegues-pour-la-vie-lyceenne.html", 
            "description": "<em>Septembre 2013 - Juin 2015</em> Délégué et sous-représentant des élèves du lycée. J'ai eu l'occasion :\n  <ul>\n    <li>d'\u00eatre porte-parole des élèves,</li>\n    <li>d'assister à des réunions pédagogiques et administratives,</li>\n    <li>de mettre en place et réaliser des projets pédagogiques,</li>\n    <li>d'organiser des év\u00eanements culturels.</li>\n  </ul>\n"
          }, 
          "name": "Délégué du CVL", 
          "ipv6_only": false, 
          "id": 12
        }, 
        {
          "data": {
            "url": "http://www.zupdeco.org/agir/devenir-tuteur-benevole", 
            "description": "<em>Sept 2016 - juin 2017</em> Enseignant tuteur pour des élèves en difficultés dans un collège à Lyon. <ul>\n    <li>Cours particuliers et collectifs,</li>\n    <li>Cours méthodiques pour l\u2019apprentissage,</li>\n    <li>Aide aux devoirs particuliers et collectifs.</li>\n</ul>\n", 
            "icon": "teacher.png"
          }, 
          "name": "Enseignant Tuteur", 
          "ipv6_only": false, 
          "id": 13
        }
      ]
    }, 
    {
      "id": 14, 
      "data": {
        "description": "Dans cette catégories, vous trouverez le listing de toutes les Compétences que j'ai acquises dans mes différentes missions ainsi que leur niveau de maîtrise. (Comme \u00e7a, vous \u00eates au courant !)\n"
      }, 
      "name": "Compétences", 
      "ipv6_only": false, 
      "children": [
        {
          "data": {
            "url": "https://www.w3schools.com/html/html_css.asp", 
            "description": "J'ai commencé à apprendre ce couple de langage en autodidacte. Ensuite, j'ai eu l'occasion de réaliser des projets avec l'universités. Pour y accéder, je vous invite à aller dans la catégories \"Projets\". <em>Niveau de maîtrise : 9/10.</em>\n", 
            "icon": "html-css.png"
          }, 
          "name": "HTML / CSS", 
          "ipv6_only": false, 
          "id": 15
        }, 
        {
          "data": {
            "url": "https://www.w3schools.com/Js/", 
            "description": "J'ai abordé le Javascript (JS) la toute première fois lors de ma première année en informatique à Lyon. J'ai aujourd'hui de très bonnes connaissances dans ce langage. <em>Niveau de maîtrise : 8.5/10.</em>\n", 
            "icon": "javascript.png"
          }, 
          "name": "Javascript", 
          "ipv6_only": false, 
          "id": 16
        }, 
        {
          "data": {
            "url": "https://www.w3schools.com/php/", 
            "description": "J'ai pu réaliser plusieurs petits projets en PHP, mais j'ai surtout pu coder un site internet fonctionnant avec une base de données dans le cadre d'une UE de ma licence. <em>Niveau de maîtrise : 7/10.</em>\n", 
            "icon": "php.png"
          }, 
          "name": "PHP", 
          "ipv6_only": false, 
          "id": 17
        }, 
        {
          "data": {
            "url": "https://www.w3schools.com/sql/", 
            "description": "Comme expliqué dans l'élément \"PHP\", j'ai pu manipuler une base de données lors du développement d'un jeu hébergé. <em>Niveau de maîtrise : 6.5/10.</em>\n", 
            "icon": "sql.png"
          }, 
          "name": "SQL", 
          "ipv6_only": false, 
          "id": 18
        }, 
        {
          "data": {
            "url": "https://www.w3schools.in/cplusplus-tutorial/", 
            "description": "Ces langages complets et adaptés pour l'apprentissage nous ont étés imposés dès la 1ère année en informatique. Ceci m'a permis d'avoir un niveau adapté dans ces langages. <em>Niveau de maîtrise : 7.5/10.</em>\n", 
            "icon": "c.png"
          }, 
          "name": "C/C++", 
          "ipv6_only": false, 
          "id": 19
        }, 
        {
          "data": {
            "url": "https://www.tutorialspoint.com/unix/", 
            "description": "Connaissance d'un système d'exploîtation (OS) UNIX ainsi que toutes les commandes permettant le développement et la navigation dans un univers aussi large que celui-ci. <em>Niveau de maîtrise : 6.75/10.</em>\n", 
            "icon": "tux.png"
          }, 
          "name": "Unix (Shell)", 
          "ipv6_only": false, 
          "id": 20
        }
      ]
    }, 
    {
      "id": 21, 
      "data": {
        "description": "Tout le long de mon cursus scolaire, j'ai choisi personnellement ou dans le cadre universitaire d'effectuer certains projets. En voici la liste.\n"
      }, 
      "name": "Projets", 
      "ipv6_only": false, 
      "children": [
        {
          "data": {
            "url": "http://persohemoreg.alwaysdata.net/works/improvemygpx/index.html", 
            "description": "Ce projet consiste en la réalisation d\u2019un site web permettant aux utilisateurs de visualiser et d\u2019éditer leurs traces GPS. Notre site est destiné aux randonneurs ou tout autres sportifs utilisant un GPS pour enregistrer l'édition de leur parcours.\n", 
            "icon": "world.png"
          }, 
          "name": "Improve my GPX", 
          "ipv6_only": false, 
          "id": 22
        }, 
        {
          "data": {
            "url": "http://persohemoreg.alwaysdata.net/works/chutbibliotheque/index.html", 
            "description": "Site humoristique et projet personnel pour faire taire les personnes qui font trop de bruits dans les bibliothèques.\n", 
            "icon": "shh.png"
          }, 
          "name": "Chut Bibliothèque", 
          "ipv6_only": false, 
          "id": 23
        }, 
        {
          "data": {
            "url": null, 
            "description": "Projet universitaire de L2, dans lequel nous avons recréé le jeu \"Croque Carotte\" avec un système de base de données.\n", 
            "icon": "salad.png"
          }, 
          "name": "Croque Salade", 
          "ipv6_only": false, 
          "id": 24
        }, 
        {
          "data": {
            "url": "http://persohemoreg.alwaysdata.net/works/testihm/index.html", 
            "description": "Projet de L2, afin de travailler sur l'aspect ergonomique et dynamique d'une page web.\n", 
            "icon": "ask.png"
          }, 
          "name": "Sondouage", 
          "ipv6_only": false, 
          "id": 25
        }, 
        {
          "data": {
            "url": "http://persohemoreg.alwaysdata.net/", 
            "description": "Page personnelle permettant d'apprendre à gérer des structures complètes, faire de la communication professionnelle et efficace.\n", 
            "icon": null
          }, 
          "name": "Page Personnelle", 
          "ipv6_only": false, 
          "id": 26
        }
      ]
    }, 
    {
      "id": 27, 
      "data": {
        "description": "Depuis que mon enfance, j'ai eu l'occasion d'apprenre des langages différents. Dans cette catégorie, je vous parlerai de mon niveau dans ces diverses langues.\n"
      }, 
      "name": "Langues", 
      "ipv6_only": false, 
      "children": [
        {
          "data": {
            "url": null, 
            "description": "L'anglais est une langue qui m'a toujours intéressé, j'ai commencé à suivre des cours d'anglais dès le CE1. J'ai eu l'opportunité d'avoir des correspondants dans le monde entier afin de développer ma pratique dans cette langue. <em>Niveau de maîtrise : 9/10</em>\n", 
            "icon": "usa.png"
          }, 
          "name": "Anglais", 
          "ipv6_only": false, 
          "id": 28
        }, 
        {
          "data": {
            "url": "https://fr.wikipedia.org/wiki/Occitan", 
            "description": "Considérée à tort comme langue régionale, l'occitan est une langue que j'ai tout d'abord pratiqué avec mes grands parents. J'ai ensuite choisi de suivre des cours au lycée afin de pouvoir passer l'épreuve optionnelle du bac dans cette langue. <em>Niveau de maîtrise : 7/10.</em>\n", 
            "icon": "occitania.png"
          }, 
          "name": "Occitan", 
          "ipv6_only": false, 
          "id": 29
        }, 
        {
          "data": {
            "url": null, 
            "description": "J'ai débuté l'apprentissage de l'espagnol en 6ème grâce au dispositif bilingue afin de pouvoir avoir un niveau assez élevé à la fin de lycée. En effet, en tant normal, nous devions commencer cette langue en 4eme. <em>Niveau de maîtrise : 5/10.</em>\n", 
            "icon": "spain.png"
          }, 
          "name": "Espagnol", 
          "ipv6_only": false, 
          "id": 30
        }
      ]
    }
  ]
}
